/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package PianoMan;

import sun.audio.*;
import java.io.*;
import javax.swing.JOptionPane;
/**
 *
 * @author jerem
 * @author arvid
 */
public class PianoMan extends javax.swing.JFrame {

    /**
     * Creates new form PianoMan
     */
    public PianoMan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
		
		//Buttons
        cSharp = new javax.swing.JButton();
        lowE = new javax.swing.JButton();
        lowC = new javax.swing.JButton();
        lowF = new javax.swing.JButton();
        lowG = new javax.swing.JButton();
        lowD = new javax.swing.JButton();
        lowA = new javax.swing.JButton();
        lowB = new javax.swing.JButton();
        highC = new javax.swing.JButton();
        highD = new javax.swing.JButton();
        dSharp = new javax.swing.JButton();
        highE = new javax.swing.JButton();
        highF = new javax.swing.JButton();
        highG = new javax.swing.JButton();
        gSharp = new javax.swing.JButton();
        aSharp = new javax.swing.JButton();
        hiCSharp = new javax.swing.JButton();
        hiDSharp = new javax.swing.JButton();
        hiFSharp = new javax.swing.JButton();
        fSharp1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(java.awt.Color.black);
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 8));
        jPanel1.setLayout(null);

        cSharp.setBackground(java.awt.Color.black);
        cSharp.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        cSharp.setForeground(new java.awt.Color(255, 255, 255));
        cSharp.setText("C#");
        cSharp.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cSharp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSharpActionPerformed(evt);
            }
        });
        jPanel1.add(cSharp);
        cSharp.setBounds(120, 310, 71, 210);

        lowE.setBackground(java.awt.Color.white);
        lowE.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lowE.setText("E");
        lowE.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lowE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowEActionPerformed(evt);
            }
        });
        jPanel1.add(lowE);
        lowE.setBounds(250, 310, 108, 360);

        lowC.setBackground(java.awt.Color.white);
        lowC.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lowC.setText("C");
        lowC.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lowC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowCActionPerformed(evt);
            }
        });
        jPanel1.add(lowC);
        lowC.setBounds(50, 310, 108, 360);

        lowF.setBackground(java.awt.Color.white);
        lowF.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lowF.setText("F");
        lowF.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lowF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowFActionPerformed(evt);
            }
        });
        jPanel1.add(lowF);
        lowF.setBounds(350, 310, 108, 360);

        lowG.setBackground(java.awt.Color.white);
        lowG.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lowG.setText("G");
        lowG.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lowG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowGActionPerformed(evt);
            }
        });
        jPanel1.add(lowG);
        lowG.setBounds(450, 310, 108, 360);

        lowD.setBackground(java.awt.Color.white);
        lowD.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lowD.setText("D");
        lowD.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lowD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowDActionPerformed(evt);
            }
        });
        jPanel1.add(lowD);
        lowD.setBounds(150, 310, 108, 360);

        lowA.setBackground(java.awt.Color.white);
        lowA.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lowA.setText("A");
        lowA.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lowA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowAActionPerformed(evt);
            }
        });
        jPanel1.add(lowA);
        lowA.setBounds(550, 310, 108, 360);

        lowB.setBackground(java.awt.Color.white);
        lowB.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lowB.setText("B");
        lowB.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lowB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowBActionPerformed(evt);
            }
        });
        jPanel1.add(lowB);
        lowB.setBounds(650, 310, 108, 360);

        highC.setBackground(java.awt.Color.white);
        highC.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        highC.setText("C");
        highC.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        highC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highCActionPerformed(evt);
            }
        });
        jPanel1.add(highC);
        highC.setBounds(750, 310, 108, 360);

        highD.setBackground(java.awt.Color.white);
        highD.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        highD.setText("D");
        highD.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        highD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highDActionPerformed(evt);
            }
        });
        jPanel1.add(highD);
        highD.setBounds(850, 310, 108, 360);

        dSharp.setBackground(java.awt.Color.black);
        dSharp.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        dSharp.setForeground(new java.awt.Color(255, 255, 255));
        dSharp.setText("D#");
        dSharp.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        dSharp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dSharpActionPerformed(evt);
            }
        });
        jPanel1.add(dSharp);
        dSharp.setBounds(220, 150, 73, 210);

        highE.setBackground(java.awt.Color.white);
        highE.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        highE.setText("E");
        highE.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        highE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highEActionPerformed(evt);
            }
        });
        jPanel1.add(highE);
        highE.setBounds(950, 310, 108, 360);

        highF.setBackground(java.awt.Color.white);
        highF.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        highF.setText("F");
        highF.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        highF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highFActionPerformed(evt);
            }
        });
        jPanel1.add(highF);
        highF.setBounds(1050, 310, 108, 360);

        highG.setBackground(java.awt.Color.white);
        highG.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        highG.setText("G");
        highG.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        highG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highGActionPerformed(evt);
            }
        });
        jPanel1.add(highG);
        highG.setBounds(1150, 310, 108, 360);

        gSharp.setBackground(java.awt.Color.black);
        gSharp.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        gSharp.setForeground(new java.awt.Color(255, 255, 255));
        gSharp.setText("G#");
        gSharp.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gSharp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gSharpActionPerformed(evt);
            }
        });
        jPanel1.add(gSharp);
        gSharp.setBounds(510, 60, 73, 210);

        aSharp.setBackground(java.awt.Color.black);
        aSharp.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        aSharp.setForeground(new java.awt.Color(255, 255, 255));
        aSharp.setText("A#");
        aSharp.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        aSharp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aSharpActionPerformed(evt);
            }
        });
        jPanel1.add(aSharp);
        aSharp.setBounds(620, 60, 73, 210);

        hiCSharp.setBackground(java.awt.Color.black);
        hiCSharp.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        hiCSharp.setForeground(new java.awt.Color(255, 255, 255));
        hiCSharp.setText("C#");
        hiCSharp.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        hiCSharp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hiCSharpActionPerformed(evt);
            }
        });
        jPanel1.add(hiCSharp);
        hiCSharp.setBounds(820, 60, 71, 210);

        hiDSharp.setBackground(java.awt.Color.black);
        hiDSharp.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        hiDSharp.setForeground(new java.awt.Color(255, 255, 255));
        hiDSharp.setText("D#");
        hiDSharp.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        hiDSharp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hiDSharpActionPerformed(evt);
            }
        });
        jPanel1.add(hiDSharp);
        hiDSharp.setBounds(930, 60, 73, 210);

        hiFSharp.setBackground(java.awt.Color.black);
        hiFSharp.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        hiFSharp.setForeground(new java.awt.Color(255, 255, 255));
        hiFSharp.setText("F#");
        hiFSharp.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        hiFSharp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hiFSharpActionPerformed(evt);
            }
        });
        jPanel1.add(hiFSharp);
        hiFSharp.setBounds(1120, 60, 69, 210);

        fSharp1.setBackground(java.awt.Color.black);
        fSharp1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        fSharp1.setForeground(new java.awt.Color(255, 255, 255));
        fSharp1.setText("F#");
        fSharp1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        fSharp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSharp1ActionPerformed(evt);
            }
        });
        jPanel1.add(fSharp1);
        fSharp1.setBounds(400, 60, 69, 210);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, -10, 1570, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cSharpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSharpActionPerformed
        InputStream iAudio;
        try
        {
           iAudio = new FileInputStream(new File ("C:\\se186\\Music_Note\\C_s.wav") );
           AudioStream iMusic = new AudioStream(iAudio);
           AudioPlayer.player.start(iMusic );
        }
        catch (IOException e)
        {
           JOptionPane.showMessageDialog(null, e);
        }      
    }//GEN-LAST:event_cSharpActionPerformed

    private void lowEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowEActionPerformed
        InputStream iAudio;
        try
        {
           iAudio = new FileInputStream(new File ("C:\\se186\\Music_Note\\E.wav") );
           AudioStream iMusic = new AudioStream(iAudio);
           AudioPlayer.player.start(iMusic );
        }
        catch (IOException e)
        {
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_lowEActionPerformed

    private void lowCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowCActionPerformed
        InputStream iAudio;
        try
        {
           iAudio = new FileInputStream(new File ("C:\\se186\\Music_Note\\C.wav") );
           AudioStream iMusic = new AudioStream(iAudio);
           AudioPlayer.player.start(iMusic );
        }
        catch (IOException e)
        {
           JOptionPane.showMessageDialog(null, e);
        }      
    }//GEN-LAST:event_lowCActionPerformed

    private void lowDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowDActionPerformed
        InputStream iAudio;
        try
        {
           iAudio = new FileInputStream(new File ("C:\\se186\\Music_Note\\D.wav") );
           AudioStream iMusic = new AudioStream(iAudio);
           AudioPlayer.player.start(iMusic );
        }
        catch (IOException e)
        {
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_lowDActionPerformed

    private void lowFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lowFActionPerformed

    private void lowGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lowGActionPerformed

    private void lowAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lowAActionPerformed

    private void lowBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lowBActionPerformed

    private void highCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_highCActionPerformed

    private void highDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_highDActionPerformed

    private void highEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_highEActionPerformed

    private void highFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_highFActionPerformed

    private void highGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_highGActionPerformed

    private void dSharpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dSharpActionPerformed
        InputStream iAudio;
        try
        {
           iAudio = new FileInputStream(new File ("C:\\se186\\Music_Note\\D_s.wav") );
           AudioStream iMusic = new AudioStream(iAudio);
           AudioPlayer.player.start(iMusic );
        }
        catch (IOException e)
        {
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_dSharpActionPerformed

    private void gSharpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gSharpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gSharpActionPerformed

    private void aSharpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aSharpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aSharpActionPerformed

    private void hiCSharpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hiCSharpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hiCSharpActionPerformed

    private void hiDSharpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hiDSharpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hiDSharpActionPerformed

    private void hiFSharpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hiFSharpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hiFSharpActionPerformed

    private void fSharp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSharp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fSharp1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PianoMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PianoMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PianoMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PianoMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PianoMan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aSharp;
    private javax.swing.JButton cSharp;
    private javax.swing.JButton dSharp;
    private javax.swing.JButton fSharp1;
    private javax.swing.JButton gSharp;
    private javax.swing.JButton hiCSharp;
    private javax.swing.JButton hiDSharp;
    private javax.swing.JButton hiFSharp;
    private javax.swing.JButton highC;
    private javax.swing.JButton highD;
    private javax.swing.JButton highE;
    private javax.swing.JButton highF;
    private javax.swing.JButton highG;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lowA;
    private javax.swing.JButton lowB;
    private javax.swing.JButton lowC;
    private javax.swing.JButton lowD;
    private javax.swing.JButton lowE;
    private javax.swing.JButton lowF;
    private javax.swing.JButton lowG;
    // End of variables declaration//GEN-END:variables
}
