/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package PianoMan;

import sun.audio.*;
import java.io.*;
import javax.swing.JOptionPane;
/**
 *
 * @author jerem
 */
public class PianoMan extends javax.swing.JFrame {

    /**
     * Creates new form PianoMan
     */
    public PianoMan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cSharp = new javax.swing.JButton();
        gSharp = new javax.swing.JButton();
        dSharp = new javax.swing.JButton();
        hiCSharp = new javax.swing.JButton();
        aSharp = new javax.swing.JButton();
        hiDSharp = new javax.swing.JButton();
        fSharp1 = new javax.swing.JButton();
        lowC = new javax.swing.JButton();
        lowE = new javax.swing.JButton();
        lowF = new javax.swing.JButton();
        lowG = new javax.swing.JButton();
        lowA = new javax.swing.JButton();
        lowD = new javax.swing.JButton();
        lowB = new javax.swing.JButton();
        highC = new javax.swing.JButton();
        highD = new javax.swing.JButton();
        highE = new javax.swing.JButton();
        highF = new javax.swing.JButton();
        openFile = new javax.swing.JButton();
        removeFile = new javax.swing.JButton();
        record = new javax.swing.JToggleButton();
        changeInstrument = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        wholeNote = new javax.swing.JButton();
        quarterNote = new javax.swing.JButton();
        eigthNote = new javax.swing.JButton();
        sixteenthNote = new javax.swing.JButton();
        halfNote = new javax.swing.JButton();
        rhythmOrganizer = new javax.swing.JPanel();
        note1 = new javax.swing.JPanel();
        note2 = new javax.swing.JPanel();
        note3 = new javax.swing.JPanel();
        note4 = new javax.swing.JPanel();
        note5 = new javax.swing.JPanel();
        note6 = new javax.swing.JPanel();
        note7 = new javax.swing.JPanel();
        note8 = new javax.swing.JPanel();
        note9 = new javax.swing.JPanel();
        note10 = new javax.swing.JPanel();
        note11 = new javax.swing.JPanel();
        note12 = new javax.swing.JPanel();
        note13 = new javax.swing.JPanel();
        playback = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(java.awt.Color.black);
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 8));
        jPanel1.setLayout(null);

        cSharp.setBackground(java.awt.Color.black);
        cSharp.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        cSharp.setForeground(new java.awt.Color(255, 255, 255));
        cSharp.setText("C#");
        cSharp.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cSharp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSharpActionPerformed(evt);
            }
        });
        jPanel1.add(cSharp);
        cSharp.setBounds(120, 310, 82, 210);

        gSharp.setBackground(java.awt.Color.black);
        gSharp.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        gSharp.setForeground(new java.awt.Color(255, 255, 255));
        gSharp.setText("G#");
        gSharp.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gSharp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gSharpActionPerformed(evt);
            }
        });
        jPanel1.add(gSharp);
        gSharp.setBounds(520, 310, 84, 210);

        dSharp.setBackground(java.awt.Color.black);
        dSharp.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        dSharp.setForeground(new java.awt.Color(255, 255, 255));
        dSharp.setText("D#");
        dSharp.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        dSharp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dSharpActionPerformed(evt);
            }
        });
        jPanel1.add(dSharp);
        dSharp.setBounds(210, 310, 85, 210);

        hiCSharp.setBackground(java.awt.Color.black);
        hiCSharp.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        hiCSharp.setForeground(new java.awt.Color(255, 255, 255));
        hiCSharp.setText("C#");
        hiCSharp.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        hiCSharp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hiCSharpActionPerformed(evt);
            }
        });
        jPanel1.add(hiCSharp);
        hiCSharp.setBounds(820, 310, 82, 210);

        aSharp.setBackground(java.awt.Color.black);
        aSharp.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        aSharp.setForeground(new java.awt.Color(255, 255, 255));
        aSharp.setText("A#");
        aSharp.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        aSharp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aSharpActionPerformed(evt);
            }
        });
        jPanel1.add(aSharp);
        aSharp.setBounds(620, 310, 84, 210);

        hiDSharp.setBackground(java.awt.Color.black);
        hiDSharp.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        hiDSharp.setForeground(new java.awt.Color(255, 255, 255));
        hiDSharp.setText("D#");
        hiDSharp.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        hiDSharp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hiDSharpActionPerformed(evt);
            }
        });
        jPanel1.add(hiDSharp);
        hiDSharp.setBounds(920, 310, 85, 210);

        fSharp1.setBackground(java.awt.Color.black);
        fSharp1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        fSharp1.setForeground(new java.awt.Color(255, 255, 255));
        fSharp1.setText("F#");
        fSharp1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        fSharp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSharp1ActionPerformed(evt);
            }
        });
        jPanel1.add(fSharp1);
        fSharp1.setBounds(420, 310, 81, 210);

        lowC.setBackground(java.awt.Color.white);
        lowC.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lowC.setText("C");
        lowC.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lowC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowCActionPerformed(evt);
            }
        });
        jPanel1.add(lowC);
        lowC.setBounds(50, 310, 108, 360);

        lowE.setBackground(java.awt.Color.white);
        lowE.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lowE.setText("E");
        lowE.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lowE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowEActionPerformed(evt);
            }
        });
        jPanel1.add(lowE);
        lowE.setBounds(250, 310, 108, 360);

        lowF.setBackground(java.awt.Color.white);
        lowF.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lowF.setText("F");
        lowF.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lowF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowFActionPerformed(evt);
            }
        });
        jPanel1.add(lowF);
        lowF.setBounds(350, 310, 108, 360);

        lowG.setBackground(java.awt.Color.white);
        lowG.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lowG.setText("G");
        lowG.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lowG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowGActionPerformed(evt);
            }
        });
        jPanel1.add(lowG);
        lowG.setBounds(450, 310, 108, 360);

        lowA.setBackground(java.awt.Color.white);
        lowA.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lowA.setText("A");
        lowA.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lowA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowAActionPerformed(evt);
            }
        });
        jPanel1.add(lowA);
        lowA.setBounds(550, 310, 108, 360);

        lowD.setBackground(java.awt.Color.white);
        lowD.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lowD.setText("D");
        lowD.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lowD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowDActionPerformed(evt);
            }
        });
        jPanel1.add(lowD);
        lowD.setBounds(150, 310, 108, 360);

        lowB.setBackground(java.awt.Color.white);
        lowB.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lowB.setText("B");
        lowB.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lowB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowBActionPerformed(evt);
            }
        });
        jPanel1.add(lowB);
        lowB.setBounds(650, 310, 108, 360);

        highC.setBackground(java.awt.Color.white);
        highC.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        highC.setText("C");
        highC.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        highC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highCActionPerformed(evt);
            }
        });
        jPanel1.add(highC);
        highC.setBounds(750, 310, 108, 360);

        highD.setBackground(java.awt.Color.white);
        highD.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        highD.setText("D");
        highD.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        highD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highDActionPerformed(evt);
            }
        });
        jPanel1.add(highD);
        highD.setBounds(850, 310, 108, 360);

        highE.setBackground(java.awt.Color.white);
        highE.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        highE.setText("E");
        highE.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        highE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highEActionPerformed(evt);
            }
        });
        jPanel1.add(highE);
        highE.setBounds(950, 310, 108, 360);

        highF.setBackground(java.awt.Color.white);
        highF.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        highF.setText("F");
        highF.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        highF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highFActionPerformed(evt);
            }
        });
        jPanel1.add(highF);
        highF.setBounds(1050, 310, 108, 360);

        openFile.setText("Open File");
        openFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileActionPerformed(evt);
            }
        });
        jPanel1.add(openFile);
        openFile.setBounds(30, 20, 220, 70);

        removeFile.setText("Remove File");
        jPanel1.add(removeFile);
        removeFile.setBounds(30, 100, 220, 60);

        record.setText("Record");
        record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordActionPerformed(evt);
            }
        });
        jPanel1.add(record);
        record.setBounds(30, 170, 220, 50);

        changeInstrument.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Piano", "Steel Drums", "Saxaphone", "Trumpet" }));
        jPanel1.add(changeInstrument);
        changeInstrument.setBounds(270, 30, 150, 40);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.setText("Enter up to 13");
        jTextField2.setBorder(null);
        jPanel2.add(jTextField2);

        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        jTextField3.setText("Notes");
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField3);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(520, 20, 560, 30);

        wholeNote.setIcon(new javax.swing.ImageIcon("/Users/brandonburt/Desktop/modifiedWholeNote.jpg")); // NOI18N
        wholeNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wholeNoteActionPerformed(evt);
            }
        });

        quarterNote.setIcon(new javax.swing.ImageIcon("/Users/brandonburt/Desktop/modifiedHalfnote.png")); // NOI18N

        eigthNote.setIcon(new javax.swing.ImageIcon("/Users/brandonburt/Desktop/modifiedQuarterNote.jpg")); // NOI18N

        sixteenthNote.setIcon(new javax.swing.ImageIcon("/Users/brandonburt/Desktop/Music Note Images/modifiedeigthNew.png")); // NOI18N

        halfNote.setIcon(new javax.swing.ImageIcon("/Users/brandonburt/Desktop/modifiedSixteenthNote.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(wholeNote, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(quarterNote, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eigthNote, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sixteenthNote, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(halfNote, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(eigthNote, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(quarterNote, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(wholeNote, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(sixteenthNote, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(halfNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sixteenthNote.getAccessibleContext().setAccessibleDescription("");

        jPanel1.add(jPanel3);
        jPanel3.setBounds(520, 50, 560, 110);

        rhythmOrganizer.setBackground(new java.awt.Color(0, 0, 0));

        note1.setBackground(new java.awt.Color(0, 0, 0));
        note1.setPreferredSize(new java.awt.Dimension(50, 100));
        rhythmOrganizer.add(note1);

        note2.setBackground(new java.awt.Color(0, 0, 0));
        note2.setPreferredSize(new java.awt.Dimension(50, 100));
        rhythmOrganizer.add(note2);

        note3.setBackground(new java.awt.Color(0, 0, 0));
        note3.setPreferredSize(new java.awt.Dimension(50, 100));
        rhythmOrganizer.add(note3);

        note4.setBackground(new java.awt.Color(0, 0, 0));
        note4.setPreferredSize(new java.awt.Dimension(50, 100));
        rhythmOrganizer.add(note4);

        note5.setBackground(new java.awt.Color(0, 0, 0));
        note5.setPreferredSize(new java.awt.Dimension(50, 100));
        rhythmOrganizer.add(note5);

        note6.setBackground(new java.awt.Color(0, 0, 0));
        note6.setPreferredSize(new java.awt.Dimension(50, 100));
        rhythmOrganizer.add(note6);

        note7.setBackground(new java.awt.Color(0, 0, 0));
        note7.setPreferredSize(new java.awt.Dimension(50, 100));
        rhythmOrganizer.add(note7);

        note8.setBackground(new java.awt.Color(0, 0, 0));
        note8.setPreferredSize(new java.awt.Dimension(50, 100));
        rhythmOrganizer.add(note8);

        note9.setBackground(new java.awt.Color(0, 0, 0));
        note9.setPreferredSize(new java.awt.Dimension(50, 100));
        rhythmOrganizer.add(note9);

        note10.setBackground(new java.awt.Color(0, 0, 0));
        note10.setPreferredSize(new java.awt.Dimension(50, 100));
        rhythmOrganizer.add(note10);

        note11.setBackground(new java.awt.Color(0, 0, 0));
        note11.setPreferredSize(new java.awt.Dimension(50, 100));
        rhythmOrganizer.add(note11);

        note12.setBackground(new java.awt.Color(0, 0, 0));
        note12.setPreferredSize(new java.awt.Dimension(50, 100));
        rhythmOrganizer.add(note12);

        note13.setBackground(new java.awt.Color(0, 0, 0));
        note13.setPreferredSize(new java.awt.Dimension(50, 100));
        rhythmOrganizer.add(note13);

        jPanel1.add(rhythmOrganizer);
        rhythmOrganizer.setBounds(430, 180, 730, 110);

        playback.setText("Playback");
        jPanel1.add(playback);
        playback.setBounds(30, 230, 220, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, -10, 1570, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cSharpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSharpActionPerformed
        InputStream iAudio;
        try
        {
           iAudio = new FileInputStream(new File ("/Users/brandonburt/Desktop/COM S 227/Music_Note/C_s.wav") );
           AudioStream iMusic = new AudioStream(iAudio);
           AudioPlayer.player.start(iMusic );
        }
        catch (IOException e)
        {
           JOptionPane.showMessageDialog(null, e);
        }      
    }//GEN-LAST:event_cSharpActionPerformed

    private void lowEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowEActionPerformed
        InputStream iAudio;
        try
        {
           iAudio = new FileInputStream(new File ("/Users/brandonburt/Desktop/COM S 227/Music_Note/E.wav") );
           AudioStream iMusic = new AudioStream(iAudio);
           AudioPlayer.player.start(iMusic );
        }
        catch (IOException e)
        {
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_lowEActionPerformed

    private void lowCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowCActionPerformed
        InputStream iAudio;
        try
        {
           iAudio = new FileInputStream(new File ("/Users/brandonburt/Desktop/COM S 227/Music_Note/C.wav") );
           AudioStream iMusic = new AudioStream(iAudio);
           AudioPlayer.player.start(iMusic );
        }
        catch (IOException e)
        {
           JOptionPane.showMessageDialog(null, e);
        }      
    }//GEN-LAST:event_lowCActionPerformed

    private void lowDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowDActionPerformed
        InputStream iAudio;
        try
        {
           iAudio = new FileInputStream(new File ("/Users/brandonburt/Desktop/COM S 227/Music_Note/D.wav") );
           AudioStream iMusic = new AudioStream(iAudio);
           AudioPlayer.player.start(iMusic );
        }
        catch (IOException e)
        {
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_lowDActionPerformed

    private void lowFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowFActionPerformed
         InputStream iAudio;
        try
        {
           iAudio = new FileInputStream(new File ("/Users/brandonburt/Desktop/COM S 227/Music_Note/F.wav") );
           AudioStream iMusic = new AudioStream(iAudio);
           AudioPlayer.player.start(iMusic );
        }
        catch (IOException e)
        {
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_lowFActionPerformed

    private void lowGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowGActionPerformed
          InputStream iAudio;
        try
        {
           iAudio = new FileInputStream(new File ("/Users/brandonburt/Desktop/COM S 227/Music_Note/G.wav") );
           AudioStream iMusic = new AudioStream(iAudio);
           AudioPlayer.player.start(iMusic );
        }
        catch (IOException e)
        {
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_lowGActionPerformed

    private void lowAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowAActionPerformed
          InputStream iAudio;
        try
        {
           iAudio = new FileInputStream(new File ("/Users/brandonburt/Desktop/COM S 227/Music_Note/A.wav") );
           AudioStream iMusic = new AudioStream(iAudio);
           AudioPlayer.player.start(iMusic );
        }
        catch (IOException e)
        {
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_lowAActionPerformed

    private void lowBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowBActionPerformed
        InputStream iAudio;
        try
        {
           iAudio = new FileInputStream(new File ("/Users/brandonburt/Desktop/COM S 227/Music_Note/B.wav") );
           AudioStream iMusic = new AudioStream(iAudio);
           AudioPlayer.player.start(iMusic );
        }
        catch (IOException e)
        {
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_lowBActionPerformed

    private void highCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highCActionPerformed
         InputStream iAudio;
        try
        {
           iAudio = new FileInputStream(new File ("/Users/brandonburt/Desktop/COM S 227/Music_Note/C1.wav") );
           AudioStream iMusic = new AudioStream(iAudio);
           AudioPlayer.player.start(iMusic );
        }
        catch (IOException e)
        {
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_highCActionPerformed

    private void highDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highDActionPerformed
         InputStream iAudio;
        try
        {
           iAudio = new FileInputStream(new File ("/Users/brandonburt/Desktop/COM S 227/Music_Note/D1.wav") );
           AudioStream iMusic = new AudioStream(iAudio);
           AudioPlayer.player.start(iMusic );
        }
        catch (IOException e)
        {
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_highDActionPerformed

    private void highEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highEActionPerformed
         InputStream iAudio;
        try
        {
           iAudio = new FileInputStream(new File ("/Users/brandonburt/Desktop/COM S 227/Music_Note/E1.wav") );
           AudioStream iMusic = new AudioStream(iAudio);
           AudioPlayer.player.start(iMusic );
        }
        catch (IOException e)
        {
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_highEActionPerformed

    private void highFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highFActionPerformed
         InputStream iAudio;
        try
        {
           iAudio = new FileInputStream(new File ("/Users/brandonburt/Desktop/COM S 227/Music_Note/F1.wav") );
           AudioStream iMusic = new AudioStream(iAudio);
           AudioPlayer.player.start(iMusic );
        }
        catch (IOException e)
        {
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_highFActionPerformed

    private void dSharpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dSharpActionPerformed
        InputStream iAudio;
        try
        {
           iAudio = new FileInputStream(new File ("/Users/brandonburt/Desktop/COM S 227/Music_Note/D_s.wav") );
           AudioStream iMusic = new AudioStream(iAudio);
           AudioPlayer.player.start(iMusic );
        }
        catch (IOException e)
        {
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_dSharpActionPerformed

    private void gSharpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gSharpActionPerformed
        InputStream iAudio;
        try
        {
           iAudio = new FileInputStream(new File ("/Users/brandonburt/Desktop/COM S 227/Music_Note/G_s.wav") );
           AudioStream iMusic = new AudioStream(iAudio);
           AudioPlayer.player.start(iMusic );
        }
        catch (IOException e)
        {
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_gSharpActionPerformed

    private void aSharpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aSharpActionPerformed
        InputStream iAudio;
        try
        {
           iAudio = new FileInputStream(new File ("/Users/brandonburt/Desktop/COM S 227/Music_Note/Bb.wav") );
           AudioStream iMusic = new AudioStream(iAudio);
           AudioPlayer.player.start(iMusic );
        }
        catch (IOException e)
        {
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_aSharpActionPerformed

    private void hiCSharpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hiCSharpActionPerformed
      InputStream iAudio;
        try
        {
           iAudio = new FileInputStream(new File ("/Users/brandonburt/Desktop/COM S 227/Music_Note/C_s1.wav") );
           AudioStream iMusic = new AudioStream(iAudio);
           AudioPlayer.player.start(iMusic );
        }
        catch (IOException e)
        {
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_hiCSharpActionPerformed

    private void hiDSharpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hiDSharpActionPerformed
          InputStream iAudio;
        try
        {
           iAudio = new FileInputStream(new File ("/Users/brandonburt/Desktop/COM S 227/Music_Note/D_s1.wav") );
           AudioStream iMusic = new AudioStream(iAudio);
           AudioPlayer.player.start(iMusic );
        }
        catch (IOException e)
        {
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_hiDSharpActionPerformed

    private void fSharp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSharp1ActionPerformed
        InputStream iAudio;
        try
        {
           iAudio = new FileInputStream(new File ("/Users/brandonburt/Desktop/COM S 227/Music_Note/F_s.wav") );
           AudioStream iMusic = new AudioStream(iAudio);
           AudioPlayer.player.start(iMusic );
        }
        catch (IOException e)
        {
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_fSharp1ActionPerformed

    private void openFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openFileActionPerformed

    private void recordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recordActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void wholeNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wholeNoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wholeNoteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PianoMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PianoMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PianoMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PianoMan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PianoMan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aSharp;
    private javax.swing.JButton cSharp;
    private javax.swing.JComboBox<String> changeInstrument;
    private javax.swing.JButton dSharp;
    private javax.swing.JButton eigthNote;
    private javax.swing.JButton fSharp1;
    private javax.swing.JButton gSharp;
    private javax.swing.JButton halfNote;
    private javax.swing.JButton hiCSharp;
    private javax.swing.JButton hiDSharp;
    private javax.swing.JButton highC;
    private javax.swing.JButton highD;
    private javax.swing.JButton highE;
    private javax.swing.JButton highF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton lowA;
    private javax.swing.JButton lowB;
    private javax.swing.JButton lowC;
    private javax.swing.JButton lowD;
    private javax.swing.JButton lowE;
    private javax.swing.JButton lowF;
    private javax.swing.JButton lowG;
    private javax.swing.JPanel note1;
    private javax.swing.JPanel note10;
    private javax.swing.JPanel note11;
    private javax.swing.JPanel note12;
    private javax.swing.JPanel note13;
    private javax.swing.JPanel note2;
    private javax.swing.JPanel note3;
    private javax.swing.JPanel note4;
    private javax.swing.JPanel note5;
    private javax.swing.JPanel note6;
    private javax.swing.JPanel note7;
    private javax.swing.JPanel note8;
    private javax.swing.JPanel note9;
    private javax.swing.JButton openFile;
    private javax.swing.JToggleButton playback;
    private javax.swing.JButton quarterNote;
    private javax.swing.JToggleButton record;
    private javax.swing.JButton removeFile;
    private javax.swing.JPanel rhythmOrganizer;
    private javax.swing.JButton sixteenthNote;
    private javax.swing.JButton wholeNote;
    // End of variables declaration//GEN-END:variables
}
