import sun.audio.*;
import java.io.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
/**
 *
 * @author jerem
 */
public class PianoManExperiment extends JFrame {
	
    private JPanel jPanel1;
	
	private JButton[] bKeys;
	private JButton[] wKeys;
	
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
		catch (Exception ex) {
			System.out.println(ex);
        }
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PianoManExperiment().setVisible(true);
            }
        });
    }
	
    /**
     * Creates new form PianoMan
     */
    public PianoManExperiment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
		bKeys = new JButton[8];
		wKeys = new JButton[12];
		Font font = new Font("Verdana", 1, 24);
		char[] sharpChar = {'C','D','F','G','A'};
		int[] sharpSpace = {90, 180, 90, 90, 180};
		int i;
		int j;
		
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(Color.black);
        jPanel1.setBorder(BorderFactory.createLineBorder(Color.WHITE, 8));
        jPanel1.setLayout(null);
		
		//Buttons:
		j = 0;
		for (i = 0; i < 8; i++) {
			bKeys[i] = new JButton();
			bKeys[i].setBackground(Color.BLACK);
			bKeys[i].setFont(font);
			bKeys[i].setForeground(Color.WHITE);
			bKeys[i].setText(sharpChar[i % 5] + "#");
			bKeys[i].setVerticalAlignment(SwingConstants.BOTTOM);
			final int index = i + 12;
			bKeys[i].addActionListener(new ActionListener() {
				public void actionPerformed(ActionEvent evt) {
					blackKeyPerformed(evt, index);
				}
			});
			jPanel1.add(bKeys[i]);
			bKeys[i].setBounds(120 + j, 310, 82, 210);
			j += sharpSpace[i % 5];
		}
		
		for (i = 0; i < 12; i++) {
			wKeys[i] = new JButton();
			//wKeys[i];
		}
		
        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, -10, 1570, 820);

        pack();
    }
	
	private void blackKeyPerformed(ActionEvent evt, int index) {
		InputStream iAudio;
		try {
			iAudio = new FileInputStream(new File("Music_Note/C_s.wav"));
			AudioStream iMusic = new AudioStream(iAudio);
			AudioPlayer.player.start(iMusic);
		}
		catch (IOException e) {
			JOptionPane.showMessageDialog(null, e);
		}
	}
	
}
